//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.10 at 02:39:29 PM KST 
//


		//@javax.xml.bind.annotation.XmlSchema(namespace="urn:epcglobal:epcis:xsd:1") 

    @javax.xml.bind.annotation.XmlSchema(namespace="urn:epcglobal:epcis:xsd:1", xmlns = {@javax.xml.bind.annotation.XmlNs(prefix = "epcis", namespaceURI="urn:epcglobal:epcis:xsd:1"),
    		@javax.xml.bind.annotation.XmlNs(prefix="xsi",   namespaceURI="http://www.w3.org/2001/XMLSchema-instance"),
    		@javax.xml.bind.annotation.XmlNs(prefix="xsd",   namespaceURI="http://www.w3.org/2001/XMLSchema")})

   
package org.oliot.model;
//import javax.xml.bind.annotation.XmlSchema;
